In [140]:

import os
import pandas as pd
import pyarrow as pa
import pyarrow.parquet as pq

import matplotlib.pyplot as plt

In [141]:

# filepath_met = "./data/datainwards.parquet"

# # read the Parquet file into a pandas dataframe
# df = pq.read_pandas(filepath_met).to_pandas()
# df = df.dropna(subset=['Crime ID'])
# df=df[["LSOA name","ward","Longitude","Latitude"]].copy()

# df.drop_duplicates(subset=['LSOA name', 'ward'], inplace=True)

# #df=df.groupby(['LSOA name']).nunique()
# #count = (df["ward"]>1).sum()
# #count
# df[250:]

In [142]:
filepath_wa = "./data/Metropolitan-street.parquet"

# read the Parquet file into a pandas dataframe
df_ward = pq.read_pandas(filepath_wa).to_pandas()
barnet_df = df_ward[df_ward['LSOA name'].str.contains('Barnet')==True]
barnetBur_df = barnet_df[barnet_df['Crime type'].str.contains('Burglary')==True]

barnet_df

,Crime ID,Month,Reported by,Falls within,Longitude,Latitude,Location,LSOA code,LSOA name,Crime type,Last outcome category,Context
2498,None,2020-05,Metropolitan Police Service,Metropolitan Police Service,-0.203995,51.656820,On or near Parking Area,E01000248,Barnet 001A,Anti-social behaviour,None,NaN
2499,None,2020-05,Metropolitan Police Service,Metropolitan Police Service,-0.210845,51.653580,On or near Blenheim Road,E01000248,Barnet 001A,Anti-social behaviour,None,NaN
2500,None,2020-05,Metropolitan Police Service,Metropolitan Police Service,-0.203995,51.656820,On or near Parking Area,E01000248,Barnet 001A,Anti-social behaviour,None,NaN
2501,None,2020-05,Metropolitan Police Service,Metropolitan Police Service,-0.204816,51.655052,On or near Stapylton Road,E01000248,Barnet 001A,Anti-social behaviour,None,NaN
2502,None,2020-05,Metropolitan Police Service,Metropolitan Police Service,-0.206355,51.656740,On or near Alston Road,E01000248,Barnet 001A,Anti-social behaviour,None,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
13064418,ab36d69c90aa7f5fc514f4b3fb3df1dac2b7280df96395...,2020-04,Metropolitan Police Service,Metropolitan Police Service,-0.210469,51.559937,On or near Parking Area,E01000143,Barnet 041D,Burglary,Under investigation,NaN
13064419,105038d2dd7cc76cad75dfb52eacbeb37a783b1c54cd6b...,2020-04,Metropolitan Police Service,Metropolitan Police Service,-0.208789,51.557538,On or near Westcroft Way,E01000143,Barnet 041D,Criminal damage and arson,Under investigation,NaN
13064420,97df6d3bfd7d528852f18720b40529046950d37d79b7a2...,2020-04,Metropolitan Police Service,Metropolitan Police Service,-0.210469,51.559937,On or near Parking Area,E01000143,Barnet 041D,Vehicle crime,Investigation complete; no suspect identified,NaN
13064421,25b12fedbf80bb6605d02e14f58ede4f2b5e19884632ad...,2020-04,Metropolitan Police Service,Metropolitan Police Service,-0.209475,51.558798,On or near Besant Road,E01000143,Barnet 041D,Violence and sexual offences,Awaiting court outcome,NaN
13064422,edfb234a4197c36c81b7b21a8d72f5f1294e9056c71a8d...,2020-04,Metropolitan Police Service,Metropolitan Police Service,-0.207804,51.556534,On or near Horton Avenue,E01000143,Barnet 041D,Violence and sexual offences,Investigation complete; no suspect identified,NaN

In [143]:
df_occupation = pd.read_csv("./data/Economic_Activity.csv")

df_occupation.iloc[:,4:] = df_occupation.iloc[:,4:].div(df_occupation['All usual residents aged 16-74 '], axis=0)
df_occupation = df_occupation.drop(['local authority code', 'local authority name', 'All usual residents aged 16-74 '], axis=1)


barnetBur_df = pd.merge(left=barnetBur_df, right=df_occupation, left_on='LSOA code', right_on='LSOA code')
#barnetBur_df

In [144]:
df_ethnic_group = pd.read_csv("./data/Ethnic_group.csv")


df_ethnic_group.iloc[:,4:] = df_ethnic_group.iloc[:,4:].div(df_ethnic_group['All usual residents'], axis=0)

df_ethnic_group = df_ethnic_group.drop(['local authority code', 'local authority name', 'All usual residents', 'Unnamed: 7'], axis=1)
df_ethnic_group

barnetBur_df = pd.merge(left=barnetBur_df, right=df_ethnic_group, left_on='LSOA code', right_on='LSOA code')
#barnetBur_df

In [145]:
df_poverty = pd.read_csv("./data/poverty.csv")




df_poverty = df_poverty.drop(['Map 2: Percentage of Children in Poverty, London LSOAs, 2010 Change in levels of Child Poverty', 'Unnamed: 3'], axis=1)


barnetBur_df = pd.merge(left=barnetBur_df, right=df_poverty, left_on='LSOA name', right_on='Unnamed: 1')
barnetBur_df

,Crime ID,Month,Reported by,Falls within,Longitude,Latitude,Location,LSOA code,LSOA name,Crime type,Last outcome category,Context,Economically active: Employee: Full-time,Economically active: Employee: Part-time,Economically active: Full-time student,Economically active: Self-employed with employees: Full-time,Economically active: Self-employed with employees: Part-time,Economically active: Self-employed without employees: Full-time,Economically active: Self-employed without employees: Part-time,Economically active: Unemployed,Economically inactive: Long-term sick or disabled,Economically inactive: Looking after home or family,Economically inactive: Other,Economically inactive: Retired,Economically inactive: Full-time students,White British,White Irish,White Gypsy/Irish Traveller,White Other,Mixed White and Asian,Mixed White and Black African,Mixed White and Black Caribbean,Mixed Other,Asian Bangladeshi,Asian Chinese,Asian Indian,Asian Pakistani,Asian Other,Black African,Black Caribbean,Black Other,Other Arab,Other Any other,Unnamed: 1,Unnamed: 2
0,48d7fae1e76d275cfecabf17efbf6fecf769966089dcae...,2020-05,Metropolitan Police Service,Metropolitan Police Service,-0.205163,51.655067,On or near Salisbury Road,E01000248,Barnet 001A,Burglary,Investigation complete; no suspect identified,NaN,0.399831,0.103973,0.024514,0.026205,0.007608,0.087067,0.065089,0.042265,0.021133,0.049873,0.014370,0.096365,0.061708,0.753161,0.034919,0.0,0.095123,0.019266,0.003010,0.007827,0.005418,0.000000,0.006623,0.024684,0.000000,0.025286,0.006623,0.006020,0.003612,0.000602,0.007827,Barnet 001A,"6,1%"
1,d1d37e3e233d650abaf3eae1d6585e33f706cebe857ffc...,2020-05,Metropolitan Police Service,Metropolitan Police Service,-0.203868,51.653824,On or near Union Street,E01000248,Barnet 001A,Burglary,Investigation complete; no suspect identified,NaN,0.399831,0.103973,0.024514,0.026205,0.007608,0.087067,0.065089,0.042265,0.021133,0.049873,0.014370,0.096365,0.061708,0.753161,0.034919,0.0,0.095123,0.019266,0.003010,0.007827,0.005418,0.000000,0.006623,0.024684,0.000000,0.025286,0.006623,0.006020,0.003612,0.000602,0.007827,Barnet 001A,"6,1%"
2,6b13c905e40eccf73feec600e87a6c70e0667b10980e95...,2020-07,Metropolitan Police Service,Metropolitan Police Service,-0.207839,51.654289,On or near The Avenue,E01000248,Barnet 001A,Burglary,Investigation complete; no suspect identified,NaN,0.399831,0.103973,0.024514,0.026205,0.007608,0.087067,0.065089,0.042265,0.021133,0.049873,0.014370,0.096365,0.061708,0.753161,0.034919,0.0,0.095123,0.019266,0.003010,0.007827,0.005418,0.000000,0.006623,0.024684,0.000000,0.025286,0.006623,0.006020,0.003612,0.000602,0.007827,Barnet 001A,"6,1%"
3,9869e99b7803ce398498332b862347626619671258ecdb...,2021-01,Metropolitan Police Service,Metropolitan Police Service,-0.205204,51.656578,On or near Strafford Road,E01000248,Barnet 001A,Burglary,Investigation complete; no suspect identified,NaN,0.399831,0.103973,0.024514,0.026205,0.007608,0.087067,0.065089,0.042265,0.021133,0.049873,0.014370,0.096365,0.061708,0.753161,0.034919,0.0,0.095123,0.019266,0.003010,0.007827,0.005418,0.000000,0.006623,0.024684,0.000000,0.025286,0.006623,0.006020,0.003612,0.000602,0.007827,Barnet 001A,"6,1%"
4,83c73a8dfb5749e2f3922ff87ae87e3f0422e3cd8c88fa...,2021-01,Metropolitan Police Service,Metropolitan Police Service,-0.203575,51.655735,On or near Shopping Area,E01000248,Barnet 001A,Burglary,Investigation complete; no suspect identified,NaN,0.399831,0.103973,0.024514,0.026205,0.007608,0.087067,0.065089,0.042265,0.021133,0.049873,0.014370,0.096365,0.061708,0.753161,0.034919,0.0,0.095123,0.019266,0.003010,0.007827,0.005418,0.000000,0.006623,0.024684,0.000000,0.025286,0.006623,0.006020,0.003612,0.000602,0.007827,Barnet 001A,"6,1%"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42661,b1091500e22e9ad0d3a00d7e7a8d9b52834450f89e4d29...,2019-11,Metropolitan Police Service,Metropolitan Police Service,-0.200203,51.648166,On or near Ellesmere Grove,E01000293,Barnet 001F,Burglary,Status update unavailable,NaN,0.392829,0.123928,0.046765,0.029618,0.004677,0.077942,0.045207,0.028839,0.017147,0.041309,0.011691,0.115355,0.064692,0.642857,0.037747,0.0,0.109175,0.016841,0.004646,0.005807,0.014518,0.013937,0.017422,0.054588,0.009292,0.022648,0.018583,0.007549,0.002323,0.005226,0.016841,Barnet 001F,"7,7%"
42662,48f8cdb05b7885d22cb314c6fbf47ac74085cd4ad860a4...,2019-12,Metropolitan Police Service,Metropolitan Police Service,-0.196775,51.648230,On or near Woodfall Avenue,E01000293,Barnet 001F,Burglary,Under investigation,NaN,0.392829,0.123928,0.046765,0.029618,0.004677,0.077942,0.045207,0.028839,0.017147,0.041309,0.011691,0.115355,0.064692,0.642857,0.037747,0.0,0.109175,0.016841,0.004646,0.005807,0.014518,0.013937,0.017422,0.054588,0.009292,0.022648,0.018583,0.007549,0.002323,0.005226,0.016841,Barnet 001F,"7,7%"
42663,33dd7b7f6454bfd56f8f88b3a54a5ad27c9709f3701ed2...,2020-01,Metropolitan Police Service,Metropolitan Police Service,-0.194423,51.648841,On or near Vale Drive,E01000293,Barnet 001F,Burglary,Investigation complete; no suspect identified,NaN,0.392829,0.123928,0.046765,0.029618,0.004677,0.077942,0.045207,0.028839,0.017147,0.041309,0.011691,0.115355,0.064692,0.642857,0.037747,0.0,0.109175,0.016841,0.004646,0.005807,0.014518,0.013937,0.017422,0.054588,0.009292,0.022648,0.018583,0.007549,0.002323,0.005226,0.016841,Barnet 001F,"7,7%"
42664,518085b2f72f44065a22b4625b3f4b5093191a44bcff52...,2020-01,Metropolitan Police Service,Metropolitan Police Service,-0.194423,51.648841,On or near Vale Drive,E01000293,Barnet 001F,Burglary,Investigation complete; no suspect identified,NaN,0.392829,0.123928,0.046765,0.029618,0.004677,0.077942,0.045207,0.028839,0.017147,0.041309,0.011691,0.115355,0.064692,0.642857,0.037747,0.0,0.109175,0.016841,0.004646,0.005807,0.014518,0.013937,0.017422,0.054588,0.009292,0.022648,0.018583,0.007549,0.002323,0.005226,0.016841,Barnet 001F,"7,7%"
42665,0715754d17ad3b171638cc6802f385d0a8e2b18f5fd8ff...,2020-02,Metropolitan Police Service,Metropolitan Police Service,-0.200128,51.652975,On or near Wood Street,E01000293,Barnet 001F,Burglary,Investigation complete; no suspect identified,NaN,0.392829,0.123928,0.046765,0.029618,0.004677,0.077942,0.045207,0.028839,0.017147,0.041309,0.011691,0.115355,0.064692,0.642857,0.037747,0.0,0.109175,0.016841,0.004646,0.005807,0.014518,0.013937,0.017422,0.054588,0.009292,0.022648,0.018583,0.007549,0.002323,0.005226,0.016841,Barnet 001F,"7,7%"

In [146]:
df = pd.read_csv('./data/LSOA_WARD.csv')
df=df[["LSOA21NM","WD22NM"]]
df= df[df['LSOA21NM'].str.contains('Barnet')==True]
df

          LSOA21NM           WD22NM
50     Barnet 032F      West Hendon
51     Barnet 022F        Woodhouse
52     Barnet 027E    West Finchley
53     Barnet 019D    West Finchley
54     Barnet 019E        Woodhouse
...            ...              ...
31808  Barnet 043A  Colindale South
31848  Barnet 043B  Colindale South
31852  Barnet 043C  Colindale South
31853  Barnet 043D  Colindale South
31855  Barnet 043E  Colindale South

[220 rows x 2 columns]

In [147]:
merged_df = pd.merge(left=barnetBur_df, right=df, left_on='LSOA name', right_on='LSOA21NM')
a=set(merged_df["LSOA name"])
len(a)

204

In [148]:
#df_den = pd.read_csv("./data/density.csv")
#df_den=df_den[["LSOA Code","Mid-2020 population","Area Sq Km","People per Sq Km"]].copy()
#df_final = pd.merge(left=merged_df, right=df_den, left_on='LSOA code', right_on='LSOA Code')

#df_final['People per Sq Km'] = pd.to_numeric(df_final['People per Sq Km'], errors='coerce')
#df_final = df_final.fillna('0')

#df_final['People per Sq Km'] = df_final['People per Sq Km'].str.replace(' ', '').astype(float)
#df_final=df_final.drop(['LSOA21NM','LSOA Code','Mid-2020 population', 'Area Sq Km'],axis=1)
#df_final
### File with no dummies
#df_final.to_parquet('ward_data.parquet')
df_final = merged_df

In [149]:






encoded_wards = pd.get_dummies(df_final['WD22NM'])
df_months = pd.get_dummies(df_final['Month'].str.split("-").str[-1].astype(int))
df_months.columns = ['jan', 'feb', 'mar', 'apr', 'may', 'jun', 'jul', 'aug', 'sep', 'okt', 'nov', 'dec']
encoded_wards.columns
df_mon = df_months.join(encoded_wards)
df_mon

,jan,feb,mar,apr,may,jun,jul,aug,sep,okt,nov,dec,Barnet Vale,Brunswick Park,Burnt Oak,Childs Hill,Colindale North,Cricklewood,East Barnet,East Finchley,Edgware,Edgwarebury,Finchley Church End,Friern Barnet,Garden Suburb,Golders Green,Hendon,High Barnet,Mill Hill,Totteridge & Woodside,Underhill,West Finchley,West Hendon,Whetstone,Woodhouse
0,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False
1,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False
2,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False
3,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False
4,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42506,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False
42507,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False
42508,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False
42509,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False
42510,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False

In [157]:

df_crimes = df_final[["Month", "Crime ID","WD22NM"]].copy()
df_crimes= df_crimes.groupby(["WD22NM","Month"]).count()


def rolling_sum2(group,y,str,s):
    group[str] = group['Crime ID'].rolling(window=y).sum().shift(s)
    return group

df_crimes = df_crimes.groupby('WD22NM', as_index=False).apply(lambda x: rolling_sum2(x,1,"1Months",1))
df_crimes.fillna(0, inplace=True)
df_crimes = df_crimes.groupby('WD22NM', as_index=False).apply(lambda x: rolling_sum2(x,2,"2Months",1))
df_crimes.fillna(0, inplace=True)
df_crimes = df_crimes.groupby('WD22NM', as_index=False).apply(lambda x: rolling_sum2(x,3,"3Months",1))
df_crimes.fillna(0, inplace=True)
df_crimes = df_crimes.groupby('WD22NM', as_index=False).apply(lambda x: rolling_sum2(x,4,"4Months",1))
df_crimes.fillna(0, inplace=True)
df_crimes = df_crimes.groupby('WD22NM', as_index=False).apply(lambda x: rolling_sum2(x,5,"5Months",1))
df_crimes.fillna(0, inplace=True)
df_crimes = df_crimes.groupby('WD22NM', as_index=False).apply(lambda x: rolling_sum2(x,6,"6Months",1))
df_crimes.fillna(0, inplace=True)
df_crimes = df_crimes.groupby('WD22NM', as_index=False).apply(lambda x: rolling_sum2(x,7,"7Months",1))
df_crimes.fillna(0, inplace=True)
df_crimes = df_crimes.groupby('WD22NM', as_index=False).apply(lambda x: rolling_sum2(x,8,"8Months",1))
df_crimes.fillna(0, inplace=True)
df_crimes = df_crimes.groupby('WD22NM', as_index=False).apply(lambda x: rolling_sum2(x,9,"9Months",1))
df_crimes.fillna(0, inplace=True)
df_crimes = df_crimes.groupby('WD22NM', as_index=False).apply(lambda x: rolling_sum2(x,10,"10Months",1))
df_crimes.fillna(0, inplace=True)
df_crimes = df_crimes.groupby('WD22NM', as_index=False).apply(lambda x: rolling_sum2(x,11,"11Months",1))
df_crimes.fillna(0, inplace=True)
df_crimes = df_crimes.groupby('WD22NM', as_index=False).apply(lambda x: rolling_sum2(x,12,"12Months",1))
df_crimes.fillna(0, inplace=True)




#Merge the count of crimes to the main dataframe
merged_df = pd.merge(df_final, df_crimes, on=['Month', 'WD22NM'], how='left')



merged_df["Month"]=pd.to_datetime(merged_df["Month"])
merged_df["Year"]=merged_df["Month"].dt.year

pd.set_option('display.max_columns', None)
merged_df=merged_df.join(df_mon)

merged_df['Unnamed: 2'] = merged_df['Unnamed: 2'].str.replace('%', '')
merged_df['Unnamed: 2'] = merged_df['Unnamed: 2'].str.replace(',', '.').astype(float)


merged_df = merged_df.drop(['Crime ID_x', 'Month', 'Reported by', 'Falls within', 'Longitude', 'Latitude', 'LSOA code', 'Location', 'LSOA name',
                            'Last outcome category', 'Context', 'Crime type', 'Unnamed: 1', 'WD22NM'], axis=1)
merged_df.head()

,Economically active: Employee: Full-time,Economically active: Employee: Part-time,Economically active: Full-time student,Economically active: Self-employed with employees: Full-time,Economically active: Self-employed with employees: Part-time,Economically active: Self-employed without employees: Full-time,Economically active: Self-employed without employees: Part-time,Economically active: Unemployed,Economically inactive: Long-term sick or disabled,Economically inactive: Looking after home or family,Economically inactive: Other,Economically inactive: Retired,Economically inactive: Full-time students,White British,White Irish,White Gypsy/Irish Traveller,White Other,Mixed White and Asian,Mixed White and Black African,Mixed White and Black Caribbean,Mixed Other,Asian Bangladeshi,Asian Chinese,Asian Indian,Asian Pakistani,Asian Other,Black African,Black Caribbean,Black Other,Other Arab,Other Any other,Unnamed: 2,LSOA21NM,Crime ID_y,1Months,2Months,3Months,4Months,5Months,6Months,7Months,8Months,9Months,10Months,11Months,12Months,Year,jan,feb,mar,apr,may,jun,jul,aug,sep,okt,nov,dec,Barnet Vale,Brunswick Park,Burnt Oak,Childs Hill,Colindale North,Cricklewood,East Barnet,East Finchley,Edgware,Edgwarebury,Finchley Church End,Friern Barnet,Garden Suburb,Golders Green,Hendon,High Barnet,Mill Hill,Totteridge & Woodside,Underhill,West Finchley,West Hendon,Whetstone,Woodhouse
0,0.399831,0.103973,0.024514,0.026205,0.007608,0.087067,0.065089,0.042265,0.021133,0.049873,0.01437,0.096365,0.061708,0.753161,0.034919,0.0,0.095123,0.019266,0.00301,0.007827,0.005418,0.0,0.006623,0.024684,0.0,0.025286,0.006623,0.00602,0.003612,0.000602,0.007827,6.1,Barnet 001A,6,2.0,10.0,16.0,29.0,36.0,43.0,60.0,69.0,77.0,85.0,96.0,107.0,2020,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False
1,0.399831,0.103973,0.024514,0.026205,0.007608,0.087067,0.065089,0.042265,0.021133,0.049873,0.01437,0.096365,0.061708,0.753161,0.034919,0.0,0.095123,0.019266,0.00301,0.007827,0.005418,0.0,0.006623,0.024684,0.0,0.025286,0.006623,0.00602,0.003612,0.000602,0.007827,6.1,Barnet 001A,6,2.0,10.0,16.0,29.0,36.0,43.0,60.0,69.0,77.0,85.0,96.0,107.0,2020,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False
2,0.399831,0.103973,0.024514,0.026205,0.007608,0.087067,0.065089,0.042265,0.021133,0.049873,0.01437,0.096365,0.061708,0.753161,0.034919,0.0,0.095123,0.019266,0.00301,0.007827,0.005418,0.0,0.006623,0.024684,0.0,0.025286,0.006623,0.00602,0.003612,0.000602,0.007827,6.1,Barnet 001A,5,3.0,9.0,11.0,19.0,25.0,38.0,45.0,52.0,69.0,78.0,86.0,94.0,2020,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False
3,0.399831,0.103973,0.024514,0.026205,0.007608,0.087067,0.065089,0.042265,0.021133,0.049873,0.01437,0.096365,0.061708,0.753161,0.034919,0.0,0.095123,0.019266,0.00301,0.007827,0.005418,0.0,0.006623,0.024684,0.0,0.025286,0.006623,0.00602,0.003612,0.000602,0.007827,6.1,Barnet 001A,7,5.0,18.0,27.0,39.0,52.0,57.0,60.0,66.0,68.0,76.0,82.0,95.0,2021,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False
4,0.399831,0.103973,0.024514,0.026205,0.007608,0.087067,0.065089,0.042265,0.021133,0.049873,0.01437,0.096365,0.061708,0.753161,0.034919,0.0,0.095123,0.019266,0.00301,0.007827,0.005418,0.0,0.006623,0.024684,0.0,0.025286,0.006623,0.00602,0.003612,0.000602,0.007827,6.1,Barnet 001A,7,5.0,18.0,27.0,39.0,52.0,57.0,60.0,66.0,68.0,76.0,82.0,95.0,2021,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False

In [158]:
#File with dummies 

merged_df.to_parquet('linearmodel.parquet')