In [19]:

import os
import pandas as pd
import pyarrow as pa
import pyarrow.parquet as pq

import matplotlib.pyplot as plt

In [6]:

# filepath_met = "./data/datainwards.parquet"

# # read the Parquet file into a pandas dataframe
# df = pq.read_pandas(filepath_met).to_pandas()
# df = df.dropna(subset=['Crime ID'])
# df=df[["LSOA name","ward","Longitude","Latitude"]].copy()

# df.drop_duplicates(subset=['LSOA name', 'ward'], inplace=True)

# #df=df.groupby(['LSOA name']).nunique()
# #count = (df["ward"]>1).sum()
# #count
# df[250:]

In [31]:
filepath_wa = "./data/Metropolitan-street.parquet"

# read the Parquet file into a pandas dataframe
df_ward = pq.read_pandas(filepath_wa).to_pandas()
barnet_df = df_ward[df_ward['LSOA name'].str.contains('Barnet')==True]
barnetBur_df = barnet_df[barnet_df['Crime type'].str.contains('Burglary')==True]

barnet_df

,Crime ID,Month,Reported by,Falls within,Longitude,Latitude,Location,LSOA code,LSOA name,Crime type,Last outcome category,Context
2498,None,2020-05,Metropolitan Police Service,Metropolitan Police Service,-0.203995,51.656820,On or near Parking Area,E01000248,Barnet 001A,Anti-social behaviour,None,NaN
2499,None,2020-05,Metropolitan Police Service,Metropolitan Police Service,-0.210845,51.653580,On or near Blenheim Road,E01000248,Barnet 001A,Anti-social behaviour,None,NaN
2500,None,2020-05,Metropolitan Police Service,Metropolitan Police Service,-0.203995,51.656820,On or near Parking Area,E01000248,Barnet 001A,Anti-social behaviour,None,NaN
2501,None,2020-05,Metropolitan Police Service,Metropolitan Police Service,-0.204816,51.655052,On or near Stapylton Road,E01000248,Barnet 001A,Anti-social behaviour,None,NaN
2502,None,2020-05,Metropolitan Police Service,Metropolitan Police Service,-0.206355,51.656740,On or near Alston Road,E01000248,Barnet 001A,Anti-social behaviour,None,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
13064418,ab36d69c90aa7f5fc514f4b3fb3df1dac2b7280df96395...,2020-04,Metropolitan Police Service,Metropolitan Police Service,-0.210469,51.559937,On or near Parking Area,E01000143,Barnet 041D,Burglary,Under investigation,NaN
13064419,105038d2dd7cc76cad75dfb52eacbeb37a783b1c54cd6b...,2020-04,Metropolitan Police Service,Metropolitan Police Service,-0.208789,51.557538,On or near Westcroft Way,E01000143,Barnet 041D,Criminal damage and arson,Under investigation,NaN
13064420,97df6d3bfd7d528852f18720b40529046950d37d79b7a2...,2020-04,Metropolitan Police Service,Metropolitan Police Service,-0.210469,51.559937,On or near Parking Area,E01000143,Barnet 041D,Vehicle crime,Investigation complete; no suspect identified,NaN
13064421,25b12fedbf80bb6605d02e14f58ede4f2b5e19884632ad...,2020-04,Metropolitan Police Service,Metropolitan Police Service,-0.209475,51.558798,On or near Besant Road,E01000143,Barnet 041D,Violence and sexual offences,Awaiting court outcome,NaN
13064422,edfb234a4197c36c81b7b21a8d72f5f1294e9056c71a8d...,2020-04,Metropolitan Police Service,Metropolitan Police Service,-0.207804,51.556534,On or near Horton Avenue,E01000143,Barnet 041D,Violence and sexual offences,Investigation complete; no suspect identified,NaN

In [37]:
df_occupation = pd.read_csv("./data/Economic_Activity.csv")

df_occupation.iloc[:,4:] = df_occupation.iloc[:,4:].div(df_occupation['All usual residents aged 16-74 '], axis=0)
df_occupation = df_occupation.drop(['local authority code', 'local authority name', 'All usual residents aged 16-74 '], axis=1)


barnetBur_df = pd.merge(left=barnetBur_df, right=df_occupation, left_on='LSOA code', right_on='LSOA code')
barnetBur_df

,Crime ID,Month,Reported by,Falls within,Longitude,Latitude,Location,LSOA code,LSOA name,Crime type,...,Economically active: Self-employed with employees: Full-time,Economically active: Self-employed with employees: Part-time,Economically active: Self-employed without employees: Full-time,Economically active: Self-employed without employees: Part-time,Economically active: Unemployed,Economically inactive: Long-term sick or disabled,Economically inactive: Looking after home or family,Economically inactive: Other,Economically inactive: Retired,Economically inactive: Full-time students
0,48d7fae1e76d275cfecabf17efbf6fecf769966089dcae...,2020-05,Metropolitan Police Service,Metropolitan Police Service,-0.205163,51.655067,On or near Salisbury Road,E01000248,Barnet 001A,Burglary,...,0.026205,0.007608,0.087067,0.065089,0.042265,0.021133,0.049873,0.014370,0.096365,0.061708
1,d1d37e3e233d650abaf3eae1d6585e33f706cebe857ffc...,2020-05,Metropolitan Police Service,Metropolitan Police Service,-0.203868,51.653824,On or near Union Street,E01000248,Barnet 001A,Burglary,...,0.026205,0.007608,0.087067,0.065089,0.042265,0.021133,0.049873,0.014370,0.096365,0.061708
2,6b13c905e40eccf73feec600e87a6c70e0667b10980e95...,2020-07,Metropolitan Police Service,Metropolitan Police Service,-0.207839,51.654289,On or near The Avenue,E01000248,Barnet 001A,Burglary,...,0.026205,0.007608,0.087067,0.065089,0.042265,0.021133,0.049873,0.014370,0.096365,0.061708
3,9869e99b7803ce398498332b862347626619671258ecdb...,2021-01,Metropolitan Police Service,Metropolitan Police Service,-0.205204,51.656578,On or near Strafford Road,E01000248,Barnet 001A,Burglary,...,0.026205,0.007608,0.087067,0.065089,0.042265,0.021133,0.049873,0.014370,0.096365,0.061708
4,83c73a8dfb5749e2f3922ff87ae87e3f0422e3cd8c88fa...,2021-01,Metropolitan Police Service,Metropolitan Police Service,-0.203575,51.655735,On or near Shopping Area,E01000248,Barnet 001A,Burglary,...,0.026205,0.007608,0.087067,0.065089,0.042265,0.021133,0.049873,0.014370,0.096365,0.061708
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42661,b1091500e22e9ad0d3a00d7e7a8d9b52834450f89e4d29...,2019-11,Metropolitan Police Service,Metropolitan Police Service,-0.200203,51.648166,On or near Ellesmere Grove,E01000293,Barnet 001F,Burglary,...,0.029618,0.004677,0.077942,0.045207,0.028839,0.017147,0.041309,0.011691,0.115355,0.064692
42662,48f8cdb05b7885d22cb314c6fbf47ac74085cd4ad860a4...,2019-12,Metropolitan Police Service,Metropolitan Police Service,-0.196775,51.648230,On or near Woodfall Avenue,E01000293,Barnet 001F,Burglary,...,0.029618,0.004677,0.077942,0.045207,0.028839,0.017147,0.041309,0.011691,0.115355,0.064692
42663,33dd7b7f6454bfd56f8f88b3a54a5ad27c9709f3701ed2...,2020-01,Metropolitan Police Service,Metropolitan Police Service,-0.194423,51.648841,On or near Vale Drive,E01000293,Barnet 001F,Burglary,...,0.029618,0.004677,0.077942,0.045207,0.028839,0.017147,0.041309,0.011691,0.115355,0.064692
42664,518085b2f72f44065a22b4625b3f4b5093191a44bcff52...,2020-01,Metropolitan Police Service,Metropolitan Police Service,-0.194423,51.648841,On or near Vale Drive,E01000293,Barnet 001F,Burglary,...,0.029618,0.004677,0.077942,0.045207,0.028839,0.017147,0.041309,0.011691,0.115355,0.064692
42665,0715754d17ad3b171638cc6802f385d0a8e2b18f5fd8ff...,2020-02,Metropolitan Police Service,Metropolitan Police Service,-0.200128,51.652975,On or near Wood Street,E01000293,Barnet 001F,Burglary,...,0.029618,0.004677,0.077942,0.045207,0.028839,0.017147,0.041309,0.011691,0.115355,0.064692

In [68]:
df = pd.read_csv('./data/LSOA_WARD.csv')
df=df[["LSOA21NM","WD22NM"]]
df= df[df['LSOA21NM'].str.contains('Barnet')==True]
df

          LSOA21NM           WD22NM
50     Barnet 032F      West Hendon
51     Barnet 022F        Woodhouse
52     Barnet 027E    West Finchley
53     Barnet 019D    West Finchley
54     Barnet 019E        Woodhouse
...            ...              ...
31808  Barnet 043A  Colindale South
31848  Barnet 043B  Colindale South
31852  Barnet 043C  Colindale South
31853  Barnet 043D  Colindale South
31855  Barnet 043E  Colindale South

[220 rows x 2 columns]

In [81]:
lista= set(df["LSOA21NM"])
f = set(df_deprivation["LSOA name (2011)"])
len(f)
q=set(barnetBur_df['LSOA name'])
a=[]

for i in lista:
    if i not in q:
        a.append(i)
a

['Barnet 043C',
 'Barnet 043F',
 'Barnet 024G',
 'Barnet 043B',
 'Barnet 017E',
 'Barnet 043D',
 'Barnet 017F',
 'Barnet 043E',
 'Barnet 042E',
 'Barnet 042F',
 'Barnet 024H',
 'Barnet 043A',
 'Barnet 042B',
 'Barnet 042A',
 'Barnet 042D',
 'Barnet 042C']

In [72]:
merged_df = pd.merge(left=barnetBur_df, right=df, left_on='LSOA name', right_on='LSOA21NM')
a=set(merged_df["LSOA name"])
len(a)

204

In [11]:
df_den = pd.read_csv("./data/density.csv")
df_den=df_den[["LSOA Code","Mid-2020 population","Area Sq Km","People per Sq Km"]].copy()
df_final = pd.merge(left=merged_df, right=df_den, left_on='LSOA code', right_on='LSOA Code')

df_final['People per Sq Km'] = df_final['People per Sq Km'].str.replace(',', '').astype(float)
df_final=df_final.drop(['LSOA21NM','LSOA Code','Mid-2020 population', 'Area Sq Km'],axis=1)
df_final
### File with no dummies
#df_final.to_parquet('ward_data.parquet')

,Crime ID,Month,Reported by,Falls within,Longitude,Latitude,Location,LSOA code,LSOA name,Crime type,...,Geographical Barriers Sub-domain Score,Wider Barriers Sub-domain Score,Indoors Sub-domain Score,Outdoors Sub-domain Score,Dependent Children aged 0-15: mid 2015 (excluding prisoners),Population aged 16-59: mid 2015 (excluding prisoners),Older population aged 60 and over: mid 2015 (excluding prisoners),Working age population 18-59/64: for use with Employment Deprivation Domain (excluding prisoners),WD22NM,People per Sq Km
0,48d7fae1e76d275cfecabf17efbf6fecf769966089dcae...,2020-05,Metropolitan Police Service,Metropolitan Police Service,-0.205163,51.655067,On or near Salisbury Road,E01000248,Barnet 001A,Burglary,...,-1.086,1.896,-0.206,0.694,364,1017,398,1025,High Barnet,6525.0
1,d1d37e3e233d650abaf3eae1d6585e33f706cebe857ffc...,2020-05,Metropolitan Police Service,Metropolitan Police Service,-0.203868,51.653824,On or near Union Street,E01000248,Barnet 001A,Burglary,...,-1.086,1.896,-0.206,0.694,364,1017,398,1025,High Barnet,6525.0
2,6b13c905e40eccf73feec600e87a6c70e0667b10980e95...,2020-07,Metropolitan Police Service,Metropolitan Police Service,-0.207839,51.654289,On or near The Avenue,E01000248,Barnet 001A,Burglary,...,-1.086,1.896,-0.206,0.694,364,1017,398,1025,High Barnet,6525.0
3,9869e99b7803ce398498332b862347626619671258ecdb...,2021-01,Metropolitan Police Service,Metropolitan Police Service,-0.205204,51.656578,On or near Strafford Road,E01000248,Barnet 001A,Burglary,...,-1.086,1.896,-0.206,0.694,364,1017,398,1025,High Barnet,6525.0
4,83c73a8dfb5749e2f3922ff87ae87e3f0422e3cd8c88fa...,2021-01,Metropolitan Police Service,Metropolitan Police Service,-0.203575,51.655735,On or near Shopping Area,E01000248,Barnet 001A,Burglary,...,-1.086,1.896,-0.206,0.694,364,1017,398,1025,High Barnet,6525.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42506,b1091500e22e9ad0d3a00d7e7a8d9b52834450f89e4d29...,2019-11,Metropolitan Police Service,Metropolitan Police Service,-0.200203,51.648166,On or near Ellesmere Grove,E01000293,Barnet 001F,Burglary,...,-0.708,1.851,-0.071,0.669,328,1056,403,1038,Underhill,6462.0
42507,48f8cdb05b7885d22cb314c6fbf47ac74085cd4ad860a4...,2019-12,Metropolitan Police Service,Metropolitan Police Service,-0.196775,51.648230,On or near Woodfall Avenue,E01000293,Barnet 001F,Burglary,...,-0.708,1.851,-0.071,0.669,328,1056,403,1038,Underhill,6462.0
42508,33dd7b7f6454bfd56f8f88b3a54a5ad27c9709f3701ed2...,2020-01,Metropolitan Police Service,Metropolitan Police Service,-0.194423,51.648841,On or near Vale Drive,E01000293,Barnet 001F,Burglary,...,-0.708,1.851,-0.071,0.669,328,1056,403,1038,Underhill,6462.0
42509,518085b2f72f44065a22b4625b3f4b5093191a44bcff52...,2020-01,Metropolitan Police Service,Metropolitan Police Service,-0.194423,51.648841,On or near Vale Drive,E01000293,Barnet 001F,Burglary,...,-0.708,1.851,-0.071,0.669,328,1056,403,1038,Underhill,6462.0
42510,0715754d17ad3b171638cc6802f385d0a8e2b18f5fd8ff...,2020-02,Metropolitan Police Service,Metropolitan Police Service,-0.200128,51.652975,On or near Wood Street,E01000293,Barnet 001F,Burglary,...,-0.708,1.851,-0.071,0.669,328,1056,403,1038,Underhill,6462.0

In [12]:






encoded_wards = pd.get_dummies(df_final['WD22NM'])
df_months = pd.get_dummies(df_final['Month'].str.split("-").str[-1].astype(int))
df_months.columns = ['jan', 'feb', 'mar', 'apr', 'may', 'jun', 'jul', 'aug', 'sep', 'okt', 'nov', 'dec']
encoded_wards.columns
df_mon = df_months.join(encoded_wards)
df_mon

,jan,feb,mar,apr,may,jun,jul,aug,sep,okt,...,Golders Green,Hendon,High Barnet,Mill Hill,Totteridge & Woodside,Underhill,West Finchley,West Hendon,Whetstone,Woodhouse
0,0,0,0,0,1,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
1,0,0,0,0,1,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
2,0,0,0,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,0,0
3,1,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
4,1,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42506,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
42507,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
42508,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
42509,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
42510,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0

In [44]:

df_crimes = df_final[["Month", "Crime ID","WD22NM"]].copy()
df_crimes= df_crimes.groupby(["WD22NM","Month"]).count()


def rolling_sum2(group,y,str,s):
    group[str] = group['Crime ID'].rolling(window=y).sum().shift(s)
    return group

df_crimes = df_crimes.groupby('WD22NM', as_index=False).apply(lambda x: rolling_sum2(x,1,"1Months",1))
df_crimes.fillna(0, inplace=True)
df_crimes = df_crimes.groupby('WD22NM', as_index=False).apply(lambda x: rolling_sum2(x,2,"2Months",1))
df_crimes.fillna(0, inplace=True)
df_crimes = df_crimes.groupby('WD22NM', as_index=False).apply(lambda x: rolling_sum2(x,3,"3Months",1))
df_crimes.fillna(0, inplace=True)
df_crimes = df_crimes.groupby('WD22NM', as_index=False).apply(lambda x: rolling_sum2(x,4,"4Months",1))
df_crimes.fillna(0, inplace=True)
df_crimes = df_crimes.groupby('WD22NM', as_index=False).apply(lambda x: rolling_sum2(x,5,"5Months",1))
df_crimes.fillna(0, inplace=True)
df_crimes = df_crimes.groupby('WD22NM', as_index=False).apply(lambda x: rolling_sum2(x,6,"6Months",1))
df_crimes.fillna(0, inplace=True)
df_crimes = df_crimes.groupby('WD22NM', as_index=False).apply(lambda x: rolling_sum2(x,7,"7Months",1))
df_crimes.fillna(0, inplace=True)
df_crimes = df_crimes.groupby('WD22NM', as_index=False).apply(lambda x: rolling_sum2(x,8,"8Months",1))
df_crimes.fillna(0, inplace=True)
df_crimes = df_crimes.groupby('WD22NM', as_index=False).apply(lambda x: rolling_sum2(x,9,"9Months",1))
df_crimes.fillna(0, inplace=True)
df_crimes = df_crimes.groupby('WD22NM', as_index=False).apply(lambda x: rolling_sum2(x,10,"10Months",1))
df_crimes.fillna(0, inplace=True)
df_crimes = df_crimes.groupby('WD22NM', as_index=False).apply(lambda x: rolling_sum2(x,11,"11Months",1))
df_crimes.fillna(0, inplace=True)
df_crimes = df_crimes.groupby('WD22NM', as_index=False).apply(lambda x: rolling_sum2(x,12,"12Months",1))
df_crimes.fillna(0, inplace=True)




#Merge the count of crimes to the main dataframe
merged_df = pd.merge(df_final, df_crimes, on=['Month', 'WD22NM'], how='left')



merged_df["Month"]=pd.to_datetime(merged_df["Month"])
merged_df["Year"]=merged_df["Month"].dt.year


merged_df=merged_df.join(df_mon)
merged_df.head()

C:\Users\20211445\AppData\Local\Temp\ipykernel_19568\44277964.py:9: FutureWarning: Not prepending group keys to the result index of transform-like apply. In the future, the group keys will be included in the index, regardless of whether the applied function returns a like-indexed object.
To preserve the previous behavior, use

	>>> .groupby(..., group_keys=False)

To adopt the future behavior and silence this warning, use

	>>> .groupby(..., group_keys=True)
  df_crimes = df_crimes.groupby('WD22NM', as_index=False).apply(lambda x: rolling_sum2(x,1,"1Months",1))
C:\Users\20211445\AppData\Local\Temp\ipykernel_19568\44277964.py:11: FutureWarning: Not prepending group keys to the result index of transform-like apply. In the future, the group keys will be included in the index, regardless of whether the applied function returns a like-indexed object.
To preserve the previous behavior, use

	>>> .groupby(..., group_keys=False)

To adopt the future behavior and silence this warning, use

	>>> .groupby(..., group_keys=True)
  df_crimes = df_crimes.groupby('WD22NM', as_index=False).apply(lambda x: rolling_sum2(x,2,"2Months",1))
C:\Users\20211445\AppData\Local\Temp\ipykernel_19568\44277964.py:13: FutureWarning: Not prepending group keys to the result index of transform-like apply. In the future, the group keys will be included in the index, regardless of whether the applied function returns a like-indexed object.
To preserve the previous behavior, use

	>>> .groupby(..., group_keys=False)

To adopt the future behavior and silence this warning, use

	>>> .groupby(..., group_keys=True)
  df_crimes = df_crimes.groupby('WD22NM', as_index=False).apply(lambda x: rolling_sum2(x,3,"3Months",1))
C:\Users\20211445\AppData\Local\Temp\ipykernel_19568\44277964.py:15: FutureWarning: Not prepending group keys to the result index of transform-like apply. In the future, the group keys will be included in the index, regardless of whether the applied function returns a like-indexed object.
To preserve the previous behavior, use

	>>> .groupby(..., group_keys=False)

To adopt the future behavior and silence this warning, use

	>>> .groupby(..., group_keys=True)
  df_crimes = df_crimes.groupby('WD22NM', as_index=False).apply(lambda x: rolling_sum2(x,4,"4Months",1))
C:\Users\20211445\AppData\Local\Temp\ipykernel_19568\44277964.py:17: FutureWarning: Not prepending group keys to the result index of transform-like apply. In the future, the group keys will be included in the index, regardless of whether the applied function returns a like-indexed object.
To preserve the previous behavior, use

	>>> .groupby(..., group_keys=False)

To adopt the future behavior and silence this warning, use

	>>> .groupby(..., group_keys=True)
  df_crimes = df_crimes.groupby('WD22NM', as_index=False).apply(lambda x: rolling_sum2(x,12,"12Months",1))
C:\Users\20211445\AppData\Local\Temp\ipykernel_19568\44277964.py:20: FutureWarning: Not prepending group keys to the result index of transform-like apply. In the future, the group keys will be included in the index, regardless of whether the applied function returns a like-indexed object.
To preserve the previous behavior, use

	>>> .groupby(..., group_keys=False)

To adopt the future behavior and silence this warning, use

	>>> .groupby(..., group_keys=True)
  df_crimes = df_crimes.groupby('WD22NM', as_index=False).apply(lambda x: rolling_sum2(x,1,"1MonthsLag",2))
C:\Users\20211445\AppData\Local\Temp\ipykernel_19568\44277964.py:22: FutureWarning: Not prepending group keys to the result index of transform-like apply. In the future, the group keys will be included in the index, regardless of whether the applied function returns a like-indexed object.
To preserve the previous behavior, use

	>>> .groupby(..., group_keys=False)

To adopt the future behavior and silence this warning, use

	>>> .groupby(..., group_keys=True)
  df_crimes = df_crimes.groupby('WD22NM', as_index=False).apply(lambda x: rolling_sum2(x,2,"2MonthsLag",3))
C:\Users\20211445\AppData\Local\Temp\ipykernel_19568\44277964.py:24: FutureWarning: Not prepending group keys to the result index of transform-like apply. In the future, the group keys will be included in the index, regardless of whether the applied function returns a like-indexed object.
To preserve the previous behavior, use

	>>> .groupby(..., group_keys=False)

To adopt the future behavior and silence this warning, use

	>>> .groupby(..., group_keys=True)
  df_crimes = df_crimes.groupby('WD22NM', as_index=False).apply(lambda x: rolling_sum2(x,3,"3MonthsLag",4))
C:\Users\20211445\AppData\Local\Temp\ipykernel_19568\44277964.py:26: FutureWarning: Not prepending group keys to the result index of transform-like apply. In the future, the group keys will be included in the index, regardless of whether the applied function returns a like-indexed object.
To preserve the previous behavior, use

	>>> .groupby(..., group_keys=False)

To adopt the future behavior and silence this warning, use

	>>> .groupby(..., group_keys=True)
  df_crimes = df_crimes.groupby('WD22NM', as_index=False).apply(lambda x: rolling_sum2(x,4,"4MonthsLag",5))

,Crime ID_x,Month,Reported by,Falls within,Longitude,Latitude,Location,LSOA code,LSOA name,Crime type,...,Golders Green,Hendon,High Barnet,Mill Hill,Totteridge & Woodside,Underhill,West Finchley,West Hendon,Whetstone,Woodhouse
0,48d7fae1e76d275cfecabf17efbf6fecf769966089dcae...,2020-05-01,Metropolitan Police Service,Metropolitan Police Service,-0.205163,51.655067,On or near Salisbury Road,E01000248,Barnet 001A,Burglary,...,0,0,1,0,0,0,0,0,0,0
1,d1d37e3e233d650abaf3eae1d6585e33f706cebe857ffc...,2020-05-01,Metropolitan Police Service,Metropolitan Police Service,-0.203868,51.653824,On or near Union Street,E01000248,Barnet 001A,Burglary,...,0,0,1,0,0,0,0,0,0,0
2,6b13c905e40eccf73feec600e87a6c70e0667b10980e95...,2020-07-01,Metropolitan Police Service,Metropolitan Police Service,-0.207839,51.654289,On or near The Avenue,E01000248,Barnet 001A,Burglary,...,0,0,1,0,0,0,0,0,0,0
3,9869e99b7803ce398498332b862347626619671258ecdb...,2021-01-01,Metropolitan Police Service,Metropolitan Police Service,-0.205204,51.656578,On or near Strafford Road,E01000248,Barnet 001A,Burglary,...,0,0,1,0,0,0,0,0,0,0
4,83c73a8dfb5749e2f3922ff87ae87e3f0422e3cd8c88fa...,2021-01-01,Metropolitan Police Service,Metropolitan Police Service,-0.203575,51.655735,On or near Shopping Area,E01000248,Barnet 001A,Burglary,...,0,0,1,0,0,0,0,0,0,0

In [51]:
#File with dummies 

merged_df.to_parquet('linearmodel.parquet')